package event

import "time"

// Generated by https://quicktype.io

type StampEvent struct {
	EventTime time.Time `json:"eventTime"`
	MessageID string    `json:"messageId"`
	Stamps    []Stamp   `json:"stamps"`
}

type Stamp struct {
	StampID   string    `json:"stampId"`
	UserID    string    `json:"userId"`
	Count     int64     `json:"count"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
